version: '3'
services:
  server:
    image: dalongrong/redash:8.0.0.b30340
    command: server
    env_file: ./opt/redash/env
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    image: dalongrong/redash:8.0.0.b30340
    command: scheduler
    env_file: ./opt/redash/env
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    image: dalongrong/redash:8.0.0.b30340
    command: worker
    env_file: ./opt/redash/env
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    image: dalongrong/redash:8.0.0.b30340
    command: worker
    env_file: ./opt/redash/env
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  redis:
    image: redis:5.0-alpine
    restart: always
  postgres:
    image: postgres:9.5-alpine
    env_file: ./opt/redash/env
    volumes:
      - ./opt/redash/postgres-data:/var/lib/postgresql/data
    restart: always
  nginx:
    image: redash/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
